remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal
title: Welcome to Danrenaline pocket dimension!
description: This is a journal of my journey into cybersecurity.
